# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/fx1/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/lge/fx1/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so

PRODUCT_COPY_FILES += \
  vendor/lge/fx1/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
  vendor/lge/fx1/proprietary/bin/hostapd:system/bin/hostapd \
  vendor/lge/fx1/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
  vendor/lge/fx1/proprietary/bin/mpdecision:system/bin/mpdecision \
  vendor/lge/fx1/proprietary/bin/netmgrd:system/bin/netmgrd \
  vendor/lge/fx1/proprietary/bin/rmt_storage:system/bin/rmt_storage \
  vendor/lge/fx1/proprietary/bin/qmuxd:system/bin/qmuxd \
  vendor/lge/fx1/proprietary/bin/thermald:system/bin/thermald \
  vendor/lge/fx1/proprietary/bin/time_daemon:system/bin/time_daemon \
  vendor/lge/fx1/proprietary/bin/cnd:system/bin/cnd \
  vendor/lge/fx1/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
  vendor/lge/fx1/proprietary/bin/port-bridge:system/bin/port-bridge \
  vendor/lge/fx1/proprietary/bin/qmiproxy:system/bin/qmiproxy \
  vendor/lge/fx1/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
  vendor/lge/fx1/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
  vendor/lge/fx1/proprietary/bin/quipc_main:system/bin/quipc_main \
  vendor/lge/fx1/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
  vendor/lge/fx1/proprietary/bin/hdmid:system/bin/hdmid \
  vendor/lge/fx1/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
  vendor/lge/fx1/proprietary/bin/rild:system/bin/rild \
  vendor/lge/fx1/proprietary/bin/ftm_ptt:system/bin/ftm_ptt \
  vendor/lge/fx1/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
  vendor/lge/fx1/proprietary/bin/qseecomd:system/bin/qseecomd \
  vendor/lge/fx1/proprietary/bin/atd:system/bin/atd \
  vendor/lge/fx1/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
  vendor/lge/fx1/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx111_default_video.so:system/lib/libchromatix_imx111_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx111_preview.so:system/lib/libchromatix_imx111_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx111_zsl.so:system/lib/libchromatix_imx111_zsl.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx119_default_video.so:system/lib/libchromatix_imx119_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx119_preview.so:system/lib/libchromatix_imx119_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_imx119_vt.so:system/lib/libchromatix_imx119_vt.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
  vendor/lge/fx1/proprietary/lib/libchromatix_s5k4e1_zsl.so:system/lib/libchromatix_s5k4e1_zsl.so \
  vendor/lge/fx1/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
  vendor/lge/fx1/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
  vendor/lge/fx1/proprietary/lib/libgemini.so:system/lib/libgemini.so \
  vendor/lge/fx1/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
  vendor/lge/fx1/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
  vendor/lge/fx1/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
  vendor/lge/fx1/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
  vendor/lge/fx1/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
  vendor/lge/fx1/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
  vendor/lge/fx1/proprietary/lib/libOlaFaceDetector.so:system/lib/libOlaFaceDetector.so \
  vendor/lge/fx1/proprietary/lib/libOlaLGECameraJNI.so:system/lib/libOlaLGECameraJNI.so \
  vendor/lge/fx1/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
  vendor/lge/fx1/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
  vendor/lge/fx1/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
  vendor/lge/fx1/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
  vendor/lge/fx1/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
  vendor/lge/fx1/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
  vendor/lge/fx1/proprietary/lib/libgps.so:system/lib/libgps.so \
  vendor/lge/fx1/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
  vendor/lge/fx1/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
  vendor/lge/fx1/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
  vendor/lge/fx1/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
  vendor/lge/fx1/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
  vendor/lge/fx1/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
  vendor/lge/fx1/proprietary/lib/libdiag.so:system/lib/libdiag.so \
  vendor/lge/fx1/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
  vendor/lge/fx1/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
  vendor/lge/fx1/proprietary/lib/libidl.so:system/lib/libidl.so \
  vendor/lge/fx1/proprietary/lib/libqdi.so:system/lib/libqdi.so \
  vendor/lge/fx1/proprietary/lib/libqdp.so:system/lib/libqdp.so \
  vendor/lge/fx1/proprietary/lib/libqmi.so:system/lib/libqmi.so \
  vendor/lge/fx1/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
  vendor/lge/fx1/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
  vendor/lge/fx1/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
  vendor/lge/fx1/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
  vendor/lge/fx1/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
  vendor/lge/fx1/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
  vendor/lge/fx1/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
  vendor/lge/fx1/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
  vendor/lge/fx1/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
  vendor/lge/fx1/proprietary/lib/libril.so:system/lib/libril.so \
  vendor/lge/fx1/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
  vendor/lge/fx1/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
  vendor/lge/fx1/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
  vendor/lge/fx1/proprietary/lib/libami306.so:system/lib/libami306.so \
  vendor/lge/fx1/proprietary/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
  vendor/lge/fx1/proprietary/lib/hw/lights.msm8960.so:system/lib/hw/lights.msm8960.so \
  vendor/lge/fx1/proprietary/lib/hw/nfc.msm8960.so:system/lib/hw/nfc.msm8960.so \
  vendor/lge/fx1/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
  vendor/lge/fx1/proprietary/libchromatix_imx111_video_default.so:system/lib/libchromatix_imx111_video_default.so
